{% set name = "fonticon-materialdesignicons7" %}
{% set version = "7.2.96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fonticon_materialdesignicons7-{{ version }}.tar.gz
  sha256: 151c800658635d1da6f168ebb808db19f97288e1f9a9a743947854a3f1690e8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - fonticon_mdi7
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyapp-kit/fonticon-materialdesignicons7
  summary: Material Design Icons 7 extension for superqt font icons
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/fonticon_mdi7/fonts/LICENSE
  doc_url: https://pyapp-kit.github.io/superqt/utilities/fonticon/

extra:
  recipe-maintainers:
    - tlambert03
